docs_dir: doc
site_dir: latest
site_name: ConCaVa
theme_dir: theme
dev_addr: 0.0.0.0:8000
pages:
    - Home: index.md
    - Introduction: introduction.md
    - Getting started: getting-started.md
    - Use cases: use-cases.md
    - Installation: installation.md
    - Configuration: configuration.md
    - API: api.md
    - Connectors: connectors.md
    - Testing: testing.md
    - Contributing: contributing.md
