docs_dir: doc
site_dir: latest
site_name: ConCaVa
theme_dir: theme
dev_addr: 0.0.0.0:8000
pages:
    - Introduction: index.md
    - Installation: installation.md
    - Configuration: configuration.md
    - "Quick Start": quick-start.md
    - API: api.md
    - Contributing: contributing.md
